src/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('password-change/', views.PasswordChangeView.as_view(),
         name='password-change'),
    path('password-reset/', views.PasswordResetView.as_view(),
         name='password-reset'),
    path('password-reset-done/', views.PasswordResetDoneView.as_view(),
         name='password-reset-done'),
    path('password-reset/<uuid:uidb64>/<slug:token>/',
         views.PasswordResetConfirmView.as_view(),
         name='password-reset-confirm'),
]

src/follow/urls.py
from django.urls import path
from . import views
from . import apps

# app_name = 'follow'
app_name = apps.FollowConfig.name
urlpatterns = [
    path('follow/person', views.FollowPerson.as_view(), name='follow_person'),
    path('follow/feed', views.FollowFeedList.as_view(), name='follow_feed'),
    path('follow/', views.FollowPeopleList.as_view(), name='follow_list'),
]

src/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'
urlpatterns = [
    path('me/', views.ShowProfile.as_view(), name='show_self'),
    path('me/edit/', views.EditProfile.as_view(), name='edit_self'),
    path('<slug:slug>/', views.ShowProfile.as_view(),
         name='show'),
]

src/search/urls.py
from django.urls import path
from . import views

app_name = 'search'
urlpatterns = [
    path('search/', views.Search.as_view(), name='search'),
]

src/templates/_brandname.html
Project Fan

src/templates/_navbar.html
<li class="nav-item{% if active_link == "home" %} active{% endif %}">
  <a class="nav-link" href="{% url 'home' %}">Home</a>
</li>
{% if user.is_authenticated %}
<li class="nav-item{% if active_link == "Feed" %} active{% endif %}">
  <a class="nav-link" href="{% url 'follow:follow_feed' %}">Feed</a>
</li>
<li class="nav-item{% if active_link == "following" %} active{% endif %}">
  <a class="nav-link" href="{% url 'follow:follow_list' %}">Following</a>
</li>
{% endif %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- <link href="{% static 'bulma/bulma.min.css' %}" rel="stylesheet"> -->
    <!-- <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script> -->
    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home' %}">
        {% block navbar-brand %}
        {% include "_brandname.html" %}
        {% endblock %}
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% block navbar-left %}{% endblock navbar-left %}
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <div class="input-group">
                <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'search:search' %}">
                  <input class="form-control mr-sm-2" type="text" name="query" placeholder="Search" aria-label="Search" aria-describedby="basic-addon2">
                  <div class="input-group-append">
                    <input class="btn btn-outline-secondary my-2 my-sm-0" type="submit" value="Search">
                  </div>
                </form>
              </div>
            </li>
            <li class="nav-item mx-2">
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li>
                  <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                {% endif %}
                <li class="nav-item dropdown">
                  <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <!-- <img src="{% thumbnail user.profile.picture|default:'default_profile.png' 20x20 crop %}" alt="" /> -->
                    {{ user.get_full_name|truncatechars:20 }}
                    <span class="caret"></span>
                  </a>

                  <div class="dropdown-menu" role="menu" aria-labelledby="navbarDropdown">
                    {#<a class="dropdown-item" href="{% url 'profiles:show_self' %}">Profile</a>#}
                    <a class="dropdown-item" href="{% url 'profiles:show_self' %}">Profile</a>
                    <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                  </div>
                </li>
              {% else %}
              <a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
              <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
              {% endif %}
            </li>
          </ul>
        </div>
      </nav>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}

    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <a name="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; Company {% now 'Y' %}</p>
          </div>
          <div class="col-lg-6 text-right">
            Connect with us on
            <a href="#"><i class="fa fa-facebook"></i> Facebook</a> or
            <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
          </div>
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

src/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block splash %}
  <div class="jumbotron jumbotron-carousel corporate-jumbo">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-8">
          <h1>{% include "_brandname.html" %}</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
	  <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up for Free!</a>
        </div>
        <div class="col-md-4 col-sm-4">

        </div>
      </div>
    </div>
  </div>
{% endblock splash %}

{% block container %}
<!-- Benefits of the Django application -->
<a name="about"></a>

<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
      <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div>
</div>

{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}